config/routes.rb
Project::Application.routes.draw do
  
  resources :posts

  resources :subcatagories

  resources :catagories

  resources :sub_catagories

  resources :catagories

  resources :laccounts

  match 'admin/' => "accounts#index", :as => :admin
  match 'accounts/:id/post' => 'accounts#post', :as => :status_post
  resources :accounts
  resource :facebook_account
  match '/callback/facebook' => "facebook_accounts#callback", :as => :facebook_callback
  resources :twitter_accounts
  resources :linkedin_accounts

  match '/callback/linkedin' => "linkedin_accounts#callback", :as => :linkedin_callback

  get "twitter_accounts/new"

  get "twitter_accounts/callback"

  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback
  resources :posts

  devise_for :users

  match 'posts/:id/publish' => 'posts#publish'

   root :to => 'home#index'

end

app/models/twitter_account.rb
require 'oauth'
class TwitterAccount < ActiveRecord::Base
  CONSUMER_KEY = '3doZvhtCs4sHi98xiCsWg'
  CONSUMER_SECRET = 'MdWBludPP2LhXRb3sm0sEpQCNgtHZ3fetiZtqT89E4'
  OPTIONS = {:site => "http://api.twitter.com", :request_endpoint => "http://api.twitter.com"}
  
  belongs_to :user
  
  
  def authorize_url(callback_url = '')
    if self.oauth_authorize_url.blank?
      # Step one, generate a request URL with a request token and secret
      signing_consumer = OAuth::Consumer.new(TwitterAccount::CONSUMER_KEY, TwitterAccount::CONSUMER_SECRET, TwitterAccount::OPTIONS)
      request_token = signing_consumer.get_request_token(
      	:oauth_callback => callback_url
      	)
      self.oauth_token = request_token.token
      self.oauth_token_secret = request_token.secret
      self.oauth_authorize_url = request_token.authorize_url
      self.save!
    end
    self.oauth_authorize_url
  end
  
  def validate_oauth_token(oauth_verifier, callback_url = '')
    begin
      signing_consumer = OAuth::Consumer.new(TwitterAccount::CONSUMER_KEY, TwitterAccount::CONSUMER_SECRET, TwitterAccount::OPTIONS)
      access_token = OAuth::RequestToken.new(signing_consumer, self.oauth_token, self.oauth_token_secret).
                                         get_access_token(:oauth_verifier => oauth_verifier)
      self.oauth_token = access_token.params[:oauth_token]
      self.oauth_token_secret = access_token.params[:oauth_token_secret]
      self.stream_url = "http://twitter.com/#{access_token.params[:screen_name]}"
      self.active = true
    rescue OAuth::Unauthorized
      self.errors.add(:oauth_token, "Invalid OAuth token, unable to connect to twitter")
      self.active = false
    end
    self.save!
  end
  
  def post(message)
    Twitter.configure do |config|
      config.consumer_key = TwitterAccount::CONSUMER_KEY
      config.consumer_secret = TwitterAccount::CONSUMER_SECRET
      config.oauth_token = self.oauth_token
      config.oauth_token_secret = self.oauth_token_secret
    end
    client = Twitter::Client.new
    begin
      client.update(message)
      return true
    rescue Exception => e
      self.errors.add(:oauth_token, "Unable to send to twitter: #{e.to_s}")
      return false
    end
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController

  # GET /twitter_accounts/new
  # GET /twitter_accounts/new.json
  def new
    @twitter_account = TwitterAccount.create(:user => current_user)
    redirect_to(@twitter_account.authorize_url(twitter_callback_url))
  end

	def callback
	   	if params[:denied] && !params[:denied].empty?
	      redirect_to(account_path(:id=>current_user.id), :alert => 'Unable to connect with twitter: #{parms[:denied]}')
	    else
	      @twitter_account = TwitterAccount.find_by_oauth_token(params[:oauth_token])
	      @twitter_account.validate_oauth_token(params[:oauth_verifier], twitter_callback_url)
	      @twitter_account.save
	      
        # 5.times do |i|
        #   @twitter_account.post("#{i}. life is beautiful!!")
           
        # end
	           	
	      
	      if @twitter_account.active?
	        redirect_to(account_path(:id=>current_user.id), :notice => 'Twitter account activated.')
	      else
	        redirect_to(account_path(:id=>current_user.id), :notice => "Unable to activate twitter account.")
	      end

	    end
	end























  # GET /twitter_accounts
  # GET /twitter_accounts.json
  def index
    @twitter_accounts = TwitterAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @twitter_accounts }
    end
  end

  # GET /twitter_accounts/1
  # GET /twitter_accounts/1.json
  def show
    @twitter_account = TwitterAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @twitter_account }
    end
  end








  # GET /twitter_accounts/1/edit
  def edit
    @twitter_account = TwitterAccount.find(params[:id])
  end

  # POST /twitter_accounts
  # POST /twitter_accounts.json
  def create
    @twitter_account = TwitterAccount.new(params[:twitter_account])

    respond_to do |format|
      if @twitter_account.save
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully created.' }
        format.json { render json: @twitter_account, status: :created, location: @twitter_account }
      else
        format.html { render action: "new" }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /twitter_accounts/1
  # PUT /twitter_accounts/1.json
  def update
    @twitter_account = TwitterAccount.find(params[:id])

    respond_to do |format|
      if @twitter_account.update_attributes(params[:twitter_account])
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_accounts/1
  # DELETE /twitter_accounts/1.json
  def destroy
    @twitter_account = TwitterAccount.find(params[:id])
    @twitter_account.destroy

    respond_to do |format|
      format.html { redirect_to twitter_accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/twitter_accounts/_form.html.erb
<%= form_for(@twitter_account) do |f| %>
  <% if @twitter_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_account.errors.count, "error") %> prohibited this twitter_account from being saved:</h2>

      <ul>
      <% @twitter_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :stream_url %><br />
    <%= f.text_area :stream_url %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br />
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_token_secret %><br />
    <%= f.text_field :oauth_token_secret %>
  </div>
  <div class="field">
    <%= f.label :oauth_token_verifier %><br />
    <%= f.text_field :oauth_token_verifier %>
  </div>
  <div class="field">
    <%= f.label :oauth_authorize_url %><br />
    <%= f.text_area :oauth_authorize_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_accounts/edit.html.erb
<h1>Editing twitter_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_account %> |
<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/index.html.erb
<h1>Listing twitter_accounts</h1>

<table>
  <tr>
    <th>Active</th>
    <th>Stream url</th>
    <th>Oauth token</th>
    <th>Oauth token secret</th>
    <th>Oauth token verifier</th>
    <th>Oauth authorize url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitter_accounts.each do |twitter_account| %>
  <tr>
    <td><%= twitter_account.active %></td>
    <td><%= twitter_account.stream_url %></td>
    <td><%= twitter_account.oauth_token %></td>
    <td><%= twitter_account.oauth_token_secret %></td>
    <td><%= twitter_account.oauth_token_verifier %></td>
    <td><%= twitter_account.oauth_authorize_url %></td>
    <td><%= link_to 'Show', twitter_account %></td>
    <td><%= link_to 'Edit', edit_twitter_account_path(twitter_account) %></td>
    <td><%= link_to 'Destroy', twitter_account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitter account', new_twitter_account_path %>

app/views/twitter_accounts/new.html.erb
<h1>New twitter_account</h1>
<%= render 'form' %>

<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Active:</b>
  <%= @twitter_account.active %>
</p>

<p>
  <b>Stream url:</b>
  <%= @twitter_account.stream_url %>
</p>

<p>
  <b>Oauth token:</b>
  <%= @twitter_account.oauth_token %>
</p>

<p>
  <b>Oauth token secret:</b>
  <%= @twitter_account.oauth_token_secret %>
</p>

<p>
  <b>Oauth token verifier:</b>
  <%= @twitter_account.oauth_token_verifier %>
</p>

<p>
  <b>Oauth authorize url:</b>
  <%= @twitter_account.oauth_authorize_url %>
</p>


<%= link_to 'Edit', edit_twitter_account_path(@twitter_account) %> |
<%= link_to 'Back', twitter_accounts_path %>