config/routes.rb
Project::Application.routes.draw do
  
  resources :posts

  resources :subcatagories

  resources :catagories

  resources :sub_catagories

  resources :catagories

  resources :laccounts

  match 'admin/' => "accounts#index", :as => :admin
  match 'accounts/:id/post' => 'accounts#post', :as => :status_post
  resources :accounts
  resource :facebook_account
  match '/callback/facebook' => "facebook_accounts#callback", :as => :facebook_callback
  resources :twitter_accounts
  resources :linkedin_accounts

  match '/callback/linkedin' => "linkedin_accounts#callback", :as => :linkedin_callback

  get "twitter_accounts/new"

  get "twitter_accounts/callback"

  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback
  resources :posts

  devise_for :users

  match 'posts/:id/publish' => 'posts#publish'

   root :to => 'home#index'

end

app/models/subcatagory.rb
class Subcatagory < ActiveRecord::Base
	belongs_to :catagory
	has_many :posts
end

app/controllers/subcatagories_controller.rb
class SubcatagoriesController < ApplicationController
  # GET /subcatagories
  # GET /subcatagories.json
  def index
    @subcatagories = Subcatagory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subcatagories }
    end
  end

  # GET /subcatagories/1
  # GET /subcatagories/1.json
  def show
    @subcatagory = Subcatagory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subcatagory }
    end
  end

  # GET /subcatagories/new
  # GET /subcatagories/new.json
  def new
    @subcatagory = Subcatagory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subcatagory }
    end
  end

  # GET /subcatagories/1/edit
  def edit
    @subcatagory = Subcatagory.find(params[:id])
  end

  # POST /subcatagories
  # POST /subcatagories.json
  def create
    @subcatagory = Subcatagory.new(params[:subcatagory])

    respond_to do |format|
      if @subcatagory.save
        format.html { redirect_to @subcatagory, notice: 'Subcatagory was successfully created.' }
        format.json { render json: @subcatagory, status: :created, location: @subcatagory }
      else
        format.html { render action: "new" }
        format.json { render json: @subcatagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subcatagories/1
  # PUT /subcatagories/1.json
  def update
    @subcatagory = Subcatagory.find(params[:id])

    respond_to do |format|
      if @subcatagory.update_attributes(params[:subcatagory])
        format.html { redirect_to @subcatagory, notice: 'Subcatagory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subcatagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcatagories/1
  # DELETE /subcatagories/1.json
  def destroy
    @subcatagory = Subcatagory.find(params[:id])
    @subcatagory.destroy

    respond_to do |format|
      format.html { redirect_to subcatagories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcatagories_helper.rb
module SubcatagoriesHelper
end

app/views/subcatagories/_form.html.erb
<%= form_for(@subcatagory) do |f| %>
  <% if @subcatagory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcatagory.errors.count, "error") %> prohibited this subcatagory from being saved:</h2>

      <ul>
      <% @subcatagory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :catagory_id %><br />
    <%= collection_select(:subcatagory, :catagory_id, Catagory.all, :id, :name) %>
    
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcatagories/edit.html.erb
<h1>Editing subcatagory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcatagory %> |
<%= link_to 'Back', subcatagories_path %>

app/views/subcatagories/index.html.erb
<h1>Listing subcatagories</h1>

<table>
  <tr>
    <th>Catagory</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcatagories.each do |subcatagory| %>
  <tr>
    <td><%= subcatagory.catagory.name if subcatagory.catagory  %></td>
    <td><%= subcatagory.name %></td>
    <td><%= link_to 'Show', subcatagory %></td>
    <td><%= link_to 'Edit', edit_subcatagory_path(subcatagory) %></td>
    <td><%= link_to 'Destroy', subcatagory, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcatagory', new_subcatagory_path %>

app/views/subcatagories/new.html.erb
<h1>New subcatagory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcatagories_path %>

app/views/subcatagories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Catagory:</b>
  <%= @subcatagory.catagory.name if @subcatagory.catagory %>
</p>

<p>
  <b>Name:</b>
  <%= @subcatagory.name %>
</p>


<%= link_to 'Edit', edit_subcatagory_path(@subcatagory) %> |
<%= link_to 'Back', subcatagories_path %>