config/routes.rb
Project::Application.routes.draw do
  
  resources :posts

  resources :subcatagories

  resources :catagories

  resources :sub_catagories

  resources :catagories

  resources :laccounts

  match 'admin/' => "accounts#index", :as => :admin
  match 'accounts/:id/post' => 'accounts#post', :as => :status_post
  resources :accounts
  resource :facebook_account
  match '/callback/facebook' => "facebook_accounts#callback", :as => :facebook_callback
  resources :twitter_accounts
  resources :linkedin_accounts

  match '/callback/linkedin' => "linkedin_accounts#callback", :as => :linkedin_callback

  get "twitter_accounts/new"

  get "twitter_accounts/callback"

  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback
  resources :posts

  devise_for :users

  match 'posts/:id/publish' => 'posts#publish'

   root :to => 'home#index'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  # GET /accounts
  # GET /accounts.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @twitter_accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @user = User.find_by_id params[:id]
    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @twitter_accounts }
    end
  end

  def post
    msg = "#{Time.now}=>life is beautiful !! "
    user = User.find_by_id params[:id]
    begin
      # if user.facebook_account and user.facebook_account.active 
      #   user.facebook_account.post(msg)
      #   #notice ='facebook '    
      # end

      if user.twitter_account and user.twitter_account.active 
        user.twitter_account.post(msg)
        #notice +='twitter '
      end

       if user.linkedin_account and user.linkedin_account.active 
         user.linkedin_account.post(msg)
         #notice += 'linkedin '    
       end
      redirect_to accounts_path , :notice => "post sent success fully to #{notice}"
 
    rescue 
      redirect_to accounts_path , :alert => 'something was wrong. try later.'

    end
  
  end
  
  def create
    
  end

  # PUT /twitter_accounts/1
end

app/views/accounts/index.html.erb
<h1>Users</h1>

<p></p>
<table>
  <tr>
    <th>user email</th>
    <th>Facebook</th>
    <th>Twitter</th>
    <th>Linkedin</th>
    <th></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= if user.facebook_account and user.facebook_account.active  
              'active ' 
            else
              'inactive '
            end %></td>

    <td><%= if user.twitter_account and user.twitter_account.active 
              'active ' 
            else
              'inactive '
            end %></td>
    <td><%= if user.linkedin_account and user.linkedin_account.active 
              'active ' 
            else
              'inactive '
            end %></td>
    <td><%= link_to 'Post ',status_post_path(:id=>user.id) %></td>

    

  </tr>
    
<% end %>


  
    
</table>

<br />
<ul>
<span><%= link_to 'posts', posts_path %></span>
<span><%= link_to 'catagories', catagories_path %></span>
<span><%= link_to 'subcatagories', subcatagories_path %></span>
</ul>

app/views/accounts/show.html.erb
<h1>available acoounts</h1>
<div>
<h2>Twitter</h2>
<p><%= link_to 'Connect Twitter account', new_twitter_account_path %></p>
<h2>facebook</h2>
<p><%= link_to 'Connect facebook account', new_facebook_account_path %></p>

<h2>Linked In</h2>
<p><%= link_to 'Connect linkedin account', new_linkedin_account_path %></p>

</div>